### ISSUE TITLE
Subtitle selector bug

### ISSUE THREAD

**Issue by NurFaizin** [PopcornTimeTV/PopcornTimeiOS#1]
Subtitle selector doesn't appear at detail episode view on TV Shows/ Anime.

### Environment

iOS 9.3.3 on iPad mini 2

### Steps to Reproduce

Subtitle selector at movie detail view works great, 
![photo181174004607985722](https://cloud.githubusercontent.com/assets/3914026/17831033/e1a1de46-6708-11e6-9afc-8beedab49f04.jpg)

but doesn't appear at detail episode view on TV Shows/ Anime
![photo181174004607985721](https://cloud.githubusercontent.com/assets/3914026/17831036/f7d6ef8a-6708-11e6-8da5-eb42be872911.jpg)

### Technical details:

* Popcorn Time Version: 0.9.154

**Comment by FlaviaBondJamesBondsHusband** [comment]
Bug fixed in latest commit. Thanks for reporting :).

**Comment by NurFaizin** [comment]
Many thanks, great works :+1:
