### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by gragera** [PopcornTimeTV/PopcornTimeiOS#27]
Hey guys,

I think https://github.com/PopcornTimeTV/Specs is a private repo so the project can not be built. If it's not intentional it would be awesome to be able to build :)

Cheers!

**Comment by FlaviaBondJamesBondsHusband** [comment]
https://github.com/PopcornTimeTV/Specs is not necessary anymore so we removed it and the project no longer depends on it. Could you try building with the latest version
