### ISSUE TITLE
blank screen

### ISSUE THREAD

**Issue by alegye2019** [PopcornTimeTV/PopcornTimeiOS#3]
Im having a problem in popcorn for IOS, When i open a movie i only have a blank screen. i have an ipad 2, can you help me?

**Comment by FlaviaBondJamesBondsHusband** [comment]
Could you be a bit more specific. What are the steps to reproduce the issue? What movie are you trying to watch? Watch OS version do you have? Are you using the latest version?

**Comment by alegye2019** [comment]
not play the movies and series turns black with playing streaming ipad 2 ios Help me have the version ios  9.3.4

**Comment by FlaviaBondJamesBondsHusband** [comment]
Working fine for me. Could you please send screenshots and make sure you have the latest version of the app by running `swift install.swift` in the terminal in the project directory.

**Comment by alegye** [comment]
![image](https://cloud.githubusercontent.com/assets/14081671/17992510/93278b0e-6b0d-11e6-9013-88440a1dffc1.png)

**Comment by alegye2019** [comment]
It puts when playing movies and anime series and leaves no image

**Comment by alegye2019** [comment]
There is the picture becomes

**Comment by alegye2019** [comment]
black video image

**Comment by alegye2019** [comment]
and I have the new version 1.0.2 ios

**Comment by alegye2019** [comment]
stable version

**Comment by FlaviaBondJamesBondsHusband** [comment]
the movie is buffering...

**Comment by alegye2019** [comment]
i only heard the sound of the movie, the movie is playing, but only sound no image.

**Comment by alegye2019** [comment]
i have IOS 9.3.4, ipad 2 64 gb, Im using the lastest version of popporntime published, adicionally the application close suddenly after a period of time
