### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by Superleo1810** [PopcornTimeTV/PopcornTimeiOS#31]
I'm a noob and followed the build guide getting 500+ errors. I made no changes in the poject at all. Anyone having the same issue or suggestions?

**Comment by FlaviaBondJamesBondsHusband** [comment]
Super sorry for this, its completely my fault. Re-follow the build guide and when it asks you what version you want make sure to choose the latest beta version (`0.1-4`).

**Comment by FlaviaBondJamesBondsHusband** [comment]
Also make sure you have the latest cocoapods version as previous versions can cause issues. If you have no idea what that means run `sudo gem install cocoapods --pre` and enter your password for your mac.

**Comment by moh0sw** [comment]
@FlaviaBondJamesBondsHusband will I guess you can help me with this error when trying to update cocoapods to 1.1.0.rc.2
( ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/xcodeproj )

any thing may be helpful?

**Comment by FlaviaBondJamesBondsHusband** [comment]
@moh0sw check out the command i gave above, super user is required to install gems. Run `sudo gem install cocoapods --pre` not `gem install cocoapods --pre`

**Comment by moh0sw** [comment]
@FlaviaBondJamesBondsHusband Thanks for the respond I used `sudo gem update -n /usr/local/bin cocoapods --pre` and it worked for me
but I'm having now a problem with the pod file on last commit with PopcornTimeTV Swift 3.0 Branch
I've opened a issue there you can see it

Thanks Again!

**Comment by Superleo1810** [comment]
@FlaviaBondJamesBondsHusband Thanks for the help. But I still can't build it and I havent figured out why. There are 19 errors, for example in line
`WatchlistManager.movie.getProgress()` it tells me that the "Value of type WatchlistManager<Movie> has no member getProgress()".
Luckily that all of these errors are errors of the WatchlistManager like this. I also tried to just delete those lines, but this caused the app to crash when opening the movie details and the video playback is impossible, because it automatically skips to the end for some reason.
Do you have some suggestions on how to resolve this without breaking the app?
Thank you again!
