### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by bubez81** [PopcornTimeTV/PopcornTimeiOS#33]
Hi! i'm trying to compile versione 1.0.3 on my iPhone 7, swift 3 but i receive this error:
![screenshot 2016-10-11 15 10 35](https://cloud.githubusercontent.com/assets/19486458/19271468/1f1fce4c-8fc5-11e6-821d-d75432684989.png)

any ideas?

**Comment by FlaviaBondJamesBondsHusband** [comment]
Issue should be fixed in latest commit
