### ISSUE TITLE
terminal error when i launch swift install.swift

### ISSUE THREAD

**Issue by bubez81** [PopcornTimeTV/PopcornTimeiOS#34]
Hi! now i receive this error when i try to swift install.swift:

`Pre-downloading: `PopcornKit` from `https://github.com/PopcornTimeTV/PopcornKit.git`, branch `new-apis`

[!] Error installing PopcornKit
[!] /usr/bin/git clone https://github.com/PopcornTimeTV/PopcornKit.git /var/folders/m4/rn87hv5n6dv64pr31kqg32280000gn/T/d20161012-4667-110w3v0 --template= --single-branch --depth 1 --branch new-apis

Cloning into '/var/folders/m4/rn87hv5n6dv64pr31kqg32280000gn/T/d20161012-4667-110w3v0'...
warning: Could not find remote branch new-apis to clone.
fatal: Remote branch new-apis not found in upstream origin

["-c", "pod update"]
Update all pods
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `PopcornKit` from `https://github.com/PopcornTimeTV/PopcornKit.git`, branch `new-apis`

[!] Error installing PopcornKit
[!] /usr/bin/git clone https://github.com/PopcornTimeTV/PopcornKit.git /var/folders/m4/rn87hv5n6dv64pr31kqg32280000gn/T/d20161012-4682-51fjmm --template= --single-branch --depth 1 --branch new-apis

Cloning into '/var/folders/m4/rn87hv5n6dv64pr31kqg32280000gn/T/d20161012-4682-51fjmm'...
warning: Could not find remote branch new-apis to clone.
fatal: Remote branch new-apis not found in upstream origin

`

**Comment by FlaviaBondJamesBondsHusband** [comment]
download the latest source

**Comment by bubez81** [comment]
sorry but this is the latest source from the master branch, downloaded now and same error

**Comment by moh0sw** [comment]
bro just run `pod repo update; pod update;`

2016-10-13 16:00 GMT+03:00 bubez81 <notifications@github.com>:

**Comment by Superleo1810** [comment]
I've got the same issue.
