### ISSUE TITLE
Error swift install.swift build dependencies

### ISSUE THREAD

**Issue by adrienbusin** [PopcornTimeTV/PopcornTimeiOS#35]
Hello, I can't build with beta version 0.1-4 because I've this error when I use swift install.swift after used pop install(cmd OK) , thanks for your help : 

Analyzing dependencies
Pre-downloading: `PopcornKit` from `https://github.com/PopcornTimeTV/PopcornKit.git`, branch `new-apis`

[!] Error installing PopcornKit
[!] /usr/bin/git clone https://github.com/PopcornTimeTV/PopcornKit.git /var/folders/3x/tq4lzj8s0yb_4n3rvbyhglxr0000gn/T/d20161017-3247-5v6kcm --template= --single-branch --depth 1 --branch new-apis

Cloning into '/var/folders/3x/tq4lzj8s0yb_4n3rvbyhglxr0000gn/T/d20161017-3247-5v6kcm'...
warning: Could not find remote branch new-apis to clone.
fatal: Remote branch new-apis not found in upstream origin

**Comment by FlaviaBondJamesBondsHusband** [comment]
Issue should be solved. Re-run the install script to fix.

**Comment by adrienbusin** [comment]
Thanks
