### ISSUE TITLE
Video player in not working with Arm7 devices for the last 2 versions

### ISSUE THREAD

**Issue by Faisal-nz** [PopcornTimeTV/PopcornTimeiOS#4]
I have tried the two latest version and it is clear that the video player is not compatible with arm7 devices as it will only show blank screen.  

an error show when i debug during a movie being pkayed 
Output of vertex shaed 'TexCoord1"  not read by fragment shader, same for TexCoord2.

Also, 199 errors in both versions was about arm7 (arm7) could bot object file symbol

**Comment by FlaviaBondJamesBondsHusband** [comment]
What is your device type? BTW all current iOS devices support arm7 instruction set. Getting 200 errors is normal when compiling for every device type.  `TexCoord1` errors are meaningless. gputoolsd is always crashing on iOS 9, they must've let the discoveryd team near it lol. Anyway we are using VLC to play all media so bug reports go to them.
