### ISSUE TITLE
the video goes black 

### ISSUE THREAD

**Issue by alegye2019** [PopcornTimeTV/PopcornTimeiOS#6]
when I go to play out the video image does not come out black and closes thank you very much not play well

**Comment by FlaviaBondJamesBondsHusband** [comment]
Please stop posting issues that make no sense.

**Comment by alegye2019** [comment]
sorry, mi english is not good. i try to explain my problem again. i install the popcorntime with xcode in mi ipad 2, everything is ok, the problem is when i open a movie, the application starts to download the movie, but when the streaming starts i only see a black screen, could you help me?
