### ISSUE TITLE
["-c", "pod install"] Cloning spec repo `popcorntimetv` from `https://github.com/PopcornTimeTV/Specs` Username for 'https://github.com': 

### ISSUE THREAD

**Issue by The1PRimeYT** [PopcornTimeTV/PopcornTimeiOS#8]
# Fetching the latest verion info...
1.0.2
1.0.0
0.9.0-0
0.2.0-0
Enter the version number: 
1.0.2

# Checking out tag 1.0.2...
["-c", "git checkout 1.0.2", "git pop"]
HEAD is now at ecdde87... Update readme
Do you have cocoapods installed? (Enter Yes or No): 
Yes
Updating and installing Cocoapods...
["-c", "rm -rf ~/.cocoapods/repos/PopcornTimeTV"]
["-c", "rm -rf Podfile.lock"]
["-c", "pod cache clean --all"]
["-c", "rm -rf ~/Library/Developer/Xcode/DerivedData/PopcornTime-*"]
["-c", "pod setup;pod repo update"]
Setting up CocoaPods master repo

CocoaPods 1.1.0.beta.1 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.1.0.beta.1

Setup completed
Updating spec repo `angryduck2`
  $ /usr/bin/git pull --ff-only
  Already up-to-date.
Updating spec repo `hackormahn`
  $ /usr/bin/git pull --ff-only
  Already up-to-date.
Updating spec repo `master`

CocoaPods 1.1.0.beta.1 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.1.0.beta.1

["-c", "pod install"]
Cloning spec repo `popcorntimetv` from `https://github.com/PopcornTimeTV/Specs`
Username for 'https://github.com':

**Comment by FlaviaBondJamesBondsHusband** [comment]
Bug fixed in latest commit. Thanks for reporting! If the fix doesnt work type `sudo rm -fr ~/.cocoapods/repos/; pod setup;` and then rerun the install script
