### ISSUE TITLE
movies dont play in iphone 4

### ISSUE THREAD

**Issue by chocolatesuper** [PopcornTimeTV/PopcornTimeiOS#9]
hi, i can't play movies in popcorntime, i install the project in mi iphone 4, when the streaming starts I only heard the voices and sound but only have a black screen, no video, after a moment the program stops working.

**Comment by FlaviaBondJamesBondsHusband** [comment]
I have no idea how you even got this project to run on an iPhone 4 as this project requires iOS 9+ and the latest Software for iPhone 4 is iOS 7.
